c_strlen name can easily clash with other libraries. I am getting:
src/standalone.f90:1:18:

    1 | program standalone
      |                  1
Error: Name ‘c_strlen’ at (1) is an ambiguous reference to ‘c_strlen’
from module ‘iwrap_tools’

unless I rename.